"""add_analyses

Revision ID: 8883cd42ad1e
Revises: 004
Create Date: 2026-05-14 10:04:46.875007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005'
down_revision: Union[str, Sequence[str], None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('analysis_type', sa.String(length=32), nullable=False),
    sa.Column('angle', sa.String(length=64), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_analysis_type', 'analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analyses_as_of_date'), 'analyses', ['as_of_date'], unique=False)
    op.create_index('ix_analyses_instrument_date', 'analyses', ['instrument_id', 'as_of_date'], unique=False)
    op.create_index(op.f('ix_analyses_instrument_id'), 'analyses', ['instrument_id'], unique=False)
    op.create_index('ix_analyses_user_id', 'analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyses_user_id', table_name='analyses')
    op.drop_index(op.f('ix_analyses_instrument_id'), table_name='analyses')
    op.drop_index('ix_analyses_instrument_date', table_name='analyses')
    op.drop_index(op.f('ix_analyses_as_of_date'), table_name='analyses')
    op.drop_index('ix_analyses_analysis_type', table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
